apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mongodb.cm.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  default.conf: |+
    storage:
      dbPath: /data/db01
    net:
      bindIp: 0.0.0.0
      port: 27017
    security:
      authorization: enabled
