---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.instance0.pvName }}
spec:
  storageClassName: {{ .Values.db.instance0.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.db.instance0.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.db.instance1.pvName }}
spec:
  storageClassName: {{ .Values.db.instance1.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.db.instance1.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.instance2.pvName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.db.instance2.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.db.instance2.storageSize }}
---  